version: "3.9"
   
services:
  db:
    image: postgres
    ports:
      - 3333:5432
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=malarkey
    volumes:
      - db-data:/var/lib/postgresql/data:delegated

  app:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:4011"
    environment:
    - DATABASE_URL=postgres://postgres:malarkey@db/postgres
    - DB_HOST=db
    - DB_NAME=app
    - DB_USER=postgres
    - DB_PASSWORD=malarkey
    volumes:
      - .:/app
    ports:
      - "4011:4011"
    depends_on:
      - db
    restart: always

volumes:
  db-data: